In [1]:
import torch

## Getting started

In [2]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
x.numel()

12

In [4]:
x.shape

torch.Size([12])

In [5]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.randn(3, 4)

tensor([[ 0.9266,  0.1338,  1.7003, -0.8461],
        [-1.7619,  2.0685,  0.1689, -1.2999],
        [-1.3689,  0.3584, -0.5607, -0.1169]])

In [9]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## Indexing and Slicing

In [10]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [11]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [12]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## Operations

In [13]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [14]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [15]:
X.reshape(-1, 3), X

(tensor([[12., 12., 12.],
         [12., 12., 12.],
         [12., 12.,  8.],
         [ 9., 10., 11.]]),
 tensor([[12., 12., 12., 12.],
         [12., 12., 12., 12.],
         [ 8.,  9., 10., 11.]]))

In [16]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [17]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
X.sum()

tensor(66.)

## Broadcasting

Broadcasting works according to the following two-step procedure: (i) expand one or both arrays by copying elements along axes with length 1 so that after this transformation, the two tensors have the same shape; (ii) perform an elementwise operation on the resulting arrays.

In [19]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [20]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## Saving Memory

In [21]:
# Python point Y to another location after dereferencing it
before = id(Y)
Y = Y + X
id(Y) == before

False

### In place operations
to perform in place operations we can overwrite the values of the tensor and replace them with the new value using slicing notation.

In [22]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2008981826016
id(Z): 2008981826016


In [23]:
before = id(X)
X += Y
id(X) == before

True

## Conversion to Other Python Objects

In [24]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [25]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# Data Preprocessing

## Reading the Dataset

In [26]:
import pandas as pd

data_file = 'data/house_tiny.csv'
data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


## Data Preparation

In [27]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True


In [28]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True


In [29]:
targets

0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64

## Conversion to Tensors

In [30]:
import torch

X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

# Linear Algebra

## Matrices

In [31]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [32]:
# Transpose
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [33]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A,A == A.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

## Tensors

 We denote general tensors by capital letters with a special font face (e.g., 
X, Y, and Z ) and their indexing mechanism (e.g.,$x_{ijk}$ and [X]$_{1,2i-1,3}$
) follows naturally from that of matrices.

In [34]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## Basic Properties of Tensor Arithmetic

### elementwise operations

In [35]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [36]:
# Hadamard product(elementwise product)
A*B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [37]:
# Scalar by tensor operation
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## Reduction

In [38]:
# summing elements
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [39]:
A[:] = 1+A

### 1. Summing Over All Elements of a Tensor

In [40]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(21.))

### 2. Summing Along Specific Axes

we can specify the axis along which the sum will be computed

In [41]:
# Axis 0 : Summing along axis 0 collapses the rows, resulting in a tensor with one less dimension (the row dimension is removed).

A.shape, A.sum(axis=0).shape

# A.sum(axis=0) sums along the rows:
# Row 1: [1, 2, 3]
# Row 2: [4, 5, 6]
# Result: [1+4, 2+5, 3+6] = [5, 7, 9]
# The output shape is (3,) because the row dimension is collapsed.

(torch.Size([2, 3]), torch.Size([3]))

In [42]:
# Axis 1 : Summing along axis 1 collapses the columns, resulting in a tensor with one less dimension (the column dimension is removed).

A.shape, A.sum(axis=1).shape

# A.sum(axis=1) sums along the columns:
# Column 1: [1, 4]
# Column 2: [2, 5]
# Column 3: [3, 6]
# Result: [1+2+3, 4+5+6] = [6, 15]
# The output shape is (2,) because the column dimension is collapsed.

(torch.Size([2, 3]), torch.Size([2]))

### 3. Summing Along Multiple Axes

You can also sum along multiple axes simultaneously by passing a list of axes to the .sum() function. This is equivalent to summing all elements of the tensor.

In [43]:
A.sum(axis=[0, 1]) == A.sum()  # Sum along both rows and columns

tensor(True)

## Non-Reduction Sum

In [44]:
A

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [45]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 6.],
         [15.]]),
 torch.Size([2, 1]))

## Dot Products

In [46]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

## Matrix–Vector Products

In [47]:
A,x

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([0., 1., 2.]))

In [48]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 8., 17.]), tensor([ 8., 17.]))

## Matrix–Matrix Multiplication

In [49]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 6.,  6.,  6.,  6.],
         [15., 15., 15., 15.]]),
 tensor([[ 6.,  6.,  6.,  6.],
         [15., 15., 15., 15.]]))

In [50]:
B,A

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]))

## Norms

In [51]:
# l2 norm
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [53]:
# l1 norm
torch.abs(u).sum()

tensor(7.)